previewsEnabled: true
previewsExpireAfterDays: 3
services:
- type: web
  name: passthrough
  branch: master
  env: static
  buildCommand: echo "hi"
  staticPublishPath: ./static/
  autoDeployFilter:
    paths:
    - static/**
    ignoredPaths:
    - one/*
    - two/**
- type: web
  name: go-server
  branch: master
  env: go
  buildCommand: cd server; go build -o app .; echo "hi"
  startCommand: cd server; ./app
  autoDeployFilter:
    paths:
    - server/**
    - foo/bar/baz/**
    - keep-adding/**
    - four/**/*
    ignoredPaths:
    - one/*
    - two/**
    - three/**
  envVars:
  - key: API_HOST
    fromService:
      name: passthrough
      type: web
      envVarKey: RENDER_EXTERNAL_URL
