previewsEnabled: true
previewsExpireAfterDays: 3
services:
- type: web
  name: passthrough
  branch: master
  env: static
  buildCommand: echo "hi"
  staticPublishPath: ./static/
  autoDeployFilter:
    paths:
    - "static/**"
    ignoredPaths:
    - "readme.md"
- type: web
  name: go-server
  branch: master
  env: go
  buildCommand: cd server; go build -o app .
  startCommand: cd server; ./app
  envVars:
  - key: API_HOST
    fromService:
      name: passthrough
      type: web
      envVarKey: RENDER_EXTERNAL_URL
