previewsEnabled: true
previewsExpireAfterDays: 3
services:
- type: web
  name: passthrough
  env: static
  buildCommand: echo "hi"
  staticPublishPath: ./static/
- type: web
  name: go-server
  env: go
  buildCommand: cd server; go build -o app .
  startCommand: cd server; ./app
  envVars:
  - key: API_HOST
    fromService:
      name: passthrough
      type: web
      envVarKey: RENDER_EXTERNAL_URL
